apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base

# El bump de versión se hace aquí: cambia newTag y ArgoCD sincroniza el deploy.
images:
  - name: ghcr.io/rasuclupe/lab-4-ghcr
    newName: ghcr.io/rasuclupe/lab-4-ghcr
    newTag: "363c8c16106984cd39e5ee672ed35b48a43d0d66"

replicas:
  - name: app
    count: 3
